.TH "cola.h" 3 "Viernes, 8 de Noviembre de 2019" "ClasePila_Max(Int)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cola.h \- Fichero cabecera del TDA \fBCola\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include '\&.\&./src/cola\&.cpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBCola< T >\fP"
.br
.RI "T\&.D\&.A\&. \fBCola\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBCola\fP\&. 

Gestiona una secuencia de elementos con facilidades para la inserción y borrado de elementos en un extremo 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClasePila_Max(Int) del código fuente\&.
