.TH "Pareja" 3 "Viernes, 8 de Noviembre de 2019" "ClasePila_Max(Int)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pareja
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBPareja\fP (const int &elem, const int &max)"
.br
.ti -1c
.RI "\fBPareja\fP & \fBoperator=\fP (const \fBPareja\fP &otra)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBelemento\fP"
.br
.ti -1c
.RI "int \fBmaximo\fP"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBPareja\fP &p)"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClasePila_Max(Int) del código fuente\&.
