Pila_max
Cola<Pareja<T> > Pila_max< T >::elementos
Cola de elementos.
T Pila_max< T >::maximo
Elemento máximo actual.
Pila_max< T >::Pila_max()
Constructor por defecto.
Pila_max< T >::Pila_max(const Pila_max &original)
Constructor de copias.
original La Pila_max de la que se hará la copia.
Pila_max< T >::~Pila_max()
Destructor.
References Pila_max< T >::operator=, Pila_max< T >::empty, Pila_max< T >::size, Pila_max< T >::top, Pila_max< T >::push, Pila_max< T >::pop.
Pila_max<T>& Pila_max< T >::operator=(const Pila_max &otra)
Operador de asignación.
otra La Pila_max que se va a asignar.
Referenced by Pila_max< T >::~Pila_max.
bool Pila_max< T >::empty() const
Comprueba si la pila está vacía.
Referenced by Pila_max< T >::~Pila_max.
int Pila_max< T >::size() const
Devuelve el tamaño de la pila.
Referenced by Pila_max< T >::~Pila_max.
Pareja<T> Pila_max< T >::top()
Devuelve el elemento del tope de la pila.
Referenced by Pila_max< T >::~Pila_max.
const Pareja<T>& Pila_max< T >::top() const
Devuelve el elemento del tope de la pila constante.
void Pila_max< T >::push(const T &nuevo)
Añade un elemento encima del tope de la pila.
nuevo Elemento que se va a añadir
Referenced by Pila_max< T >::~Pila_max.
void Pila_max< T >::pop()
Quita el elemento del tope de la pila.
Referenced by Pila_max< T >::~Pila_max.
ostream& operator<<(ostream &os, const Pila_max< U > &p)