.TH "bolsaletras.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bolsaletras.h \- Fichero cabecera del TDA \fBBolsaLetras\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'diccionario\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBBolsaLetras\fP"
.br
.RI "T\&.D\&.A\&. \fBBolsaLetras\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBBolsaLetras\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
