.TH "conjuntoletras.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conjuntoletras.h \- Fichero cabecera del TDA \fBConjuntoLetras\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <set>\fP
.br
\fC#include 'letra\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBConjuntoLetras\fP"
.br
.RI "T\&.D\&.A\&. \fBConjuntoLetras\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBConjuntoLetras\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
