.TH "diccionario.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diccionario.h \- Fichero cabecera del TDA \fBDiccionario\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <set>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBDiccionario\fP"
.br
.RI "T\&.D\&.A\&. \fBDiccionario\fP\&. "
.ti -1c
.RI "class \fBDiccionario::iterator\fP"
.br
.RI "Iterador sobre la clase \fBDiccionario\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBDiccionario\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
