.TH "Diccionario::iterator" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diccionario::iterator \- Iterador sobre la clase \fBDiccionario\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diccionario\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &i)"
.br
.ti -1c
.RI "string \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBDiccionario\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Iterador sobre la clase \fBDiccionario\fP\&. 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
