.TH "juego.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
juego.h \- Fichero cabecera del TDA \fBJuego\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'juegoletras\&.h'\fP
.br
\fC#include 'juegocifras\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBJuego\fP"
.br
.RI "T\&.D\&.A\&. \fBJuego\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBJuego\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
