.TH "juegocifras.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
juegocifras.h \- Fichero cabecera del TDA \fBJuegoCifras\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBJuegoCifras\fP"
.br
.RI "T\&.D\&.A\&. \fBJuegoCifras\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBJuegoCifras\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
