.TH "JuegoCifras" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JuegoCifras \- T\&.D\&.A\&. \fBJuegoCifras\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <juegocifras\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBJuegoCifras\fP ()"
.br
.RI "Constructor por defecto\&. "
.ti -1c
.RI "void \fBinicializarTurno\fP ()"
.br
.RI "Función que inicializa una partida, obteniendo los 6 números y el objetivo\&. "
.ti -1c
.RI "void \fBpausaTerminar\fP ()"
.br
.RI "Función que imita una pausa para que el jugador piense\&. "
.ti -1c
.RI "void \fBplay\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
T\&.D\&.A\&. \fBJuegoCifras\fP\&. 

Permite jugar partidas de Cifras\&.
.PP
Juan Francisco Díaz Moreno, mim42 (https://github.com/mim42/countdown-solver) 
.PP
\fBFecha:\fP
.RS 4
Enero 2020 
.RE
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
