.TH "letra.h" 3 "Sábado, 4 de Enero de 2020" "CifrasyLetras" \" -*- nroff -*-
.ad l
.nh
.SH NAME
letra.h \- Fichero cabecera del TDA \fBLetra\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBLetra\fP"
.br
.RI "T\&.D\&.A\&. \fBLetra\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBLetra\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para CifrasyLetras del código fuente\&.
