.TH "Mi_Fecha_Historica.h" 3 "Martes, 29 de Octubre de 2019" "ClaseMi_Cronologia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mi_Fecha_Historica.h \- Fichero de cabecera del TDA \fBMi_Fecha_Historica\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cassert>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBMi_Fecha_Historica\fP"
.br
.RI "TDA \fBMi_Fecha_Historica\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero de cabecera del TDA \fBMi_Fecha_Historica\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseMi_Cronologia del código fuente\&.
