.TH "Pareja< T >" 3 "Viernes, 8 de Noviembre de 2019" "ClasePila_Max(Template)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pareja< T >
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBPareja\fP (const T &elem, const T &max)"
.br
.ti -1c
.RI "\fBPareja\fP< T > & \fBoperator=\fP (const \fBPareja\fP< T > &otra)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBelemento\fP"
.br
.ti -1c
.RI "T \fBmaximo\fP"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "template<class U > ostream & \fBoperator<<\fP (ostream &os, const \fBPareja\fP< U > &p)"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClasePila_Max(Template) del código fuente\&.
