.TH "pila_max.h" 3 "Viernes, 8 de Noviembre de 2019" "ClasePila_Max(Template)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pila_max.h \- Fichero cabecera del TDA Pila max\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'cola\&.h'\fP
.br
\fC#include 'pareja\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include '\&.\&./src/pila_max\&.cpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPila_max< T >\fP"
.br
.RI "T\&.D\&.A\&. \fBPila_max\fP\&. "
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA Pila max\&. 

Gestiona una secuencia de elementos con facilidades para la inserción y borrado de elementos en un extremo\&. 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClasePila_Max(Template) del código fuente\&.
